# Generated by Django 4.1.7 on 2023-04-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tabela_preco_rotativo_mensalista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensalista',
            old_name='observações',
            new_name='observacoes',
        ),
    ]
