# Generated by Django 4.1.7 on 2023-05-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_observações_mensalista_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotativo',
            name='horaSaida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora saida'),
        ),
    ]
